### ISSUE TITLE
【tenth】改修事項

### ISSUE THREAD

**Issue by n-komatsu** [gizumo-inc/jquery_curriculum#4]
- liタグにクラスをつけずにaタグにつける
- テンプレートのクォーテーションを統一
- クリックイベントはaタグにつける
- 検索結果が0件の場合はページャー非表示
- e.preventDefault()
- $(document).on(‘click’)
- pager系のDOMの取得はdata属性セレクタ使用
- `<div class=“message”></div>`を初めから書いておく
- 「検索する」ボタン押下時のみキーワード変更
- 「これ以上ありません」削除->取得件数/総件数をページャー上部に表示

**Comment by Sota0403** [comment]
aタグの'#'は使わないようにする
